version: '3.9'
services:
  series-db:
    image: bitnami/mongodb:latest
    container_name: dh-series-mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGODB_ROOT_PASWWORD: ${MONGODB_ROOT_PASSWORD:-}
      MONGODB_PORT_NUMBER: '27017'
    volumes:
      - series-db:/bitnami/mongodb

  catalog-db:
    image: bitnami/mongodb:latest
    container_name: dh-catalog-mongodb
    restart: always
    ports:
      - '27018:27018'
    environment:
      MONGODB_ROOT_PASWWORD: ${MONGODB_ROOT_PASSWORD:-}
      MONGODB_PORT_NUMBER: '27018'
    volumes:
      - catalog-db:/bitnami/mongodb

  movie-db:
    image: bitnami/mongodb:latest
    container_name: dh-movie-mongodb
    restart: always
    ports:
      - '27019:27019'
    environment:
      MONGODB_ROOT_PASWWORD: ${MONGODB_ROOT_PASSWORD:-}
      MONGODB_PORT_NUMBER: '27019'
    volumes:
      - movies-db:/bitnami/mongodb

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dh-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  zipkin:
    image: openzipkin/zipkin:2
    container_name: dh-zipkin
    ports:
      - '9411:9411'
    depends_on:
      rabbitmq:
        condition: service_started

  config-service:
    image: dh/config-service:latest
    build: ./config-server
    container_name: dh-config-service
    ports:
      - '8888:8888'
    depends_on:
      - zipkin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 6

  registry-service:
    image: dh/eureka-server:latest
    build: ./eureka-server
    container_name: dh-eureka-server
    ports:
      - '8761:8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 3s
      retries: 6
    depends_on:
      config-service:
        condition: service_healthy

  gateway-service:
    image: dh/api-gateway:latest
    build: ./api-gateway
    container_name: dh-api-gateway
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 3s
      retries: 6
    depends_on:
      config-service:
        condition: service_healthy
      registry-service:
        condition: service_healthy

  movie-service:
    image: dh/movie-service:latest
    build: ./movie-service
    container_name: dh-movie-service
    ports:
      - '8097:8097'
    depends_on:
      movie-db:
        condition: service_started
      config-service:
        condition: service_healthy
      registry-service:
        condition: service_healthy

  series-service:
    image: dh/series-service:latest
    build: ./series-service
    container_name: dh-series-service
    ports:
      - '8098:8098'
    depends_on:
      series-db:
        condition: service_started
      config-service:
        condition: service_healthy
      registry-service:
        condition: service_healthy

  catalog-service:
    image: dh/catalog-service:latest
    build: ./catalog-service
    container_name: dh-catalog-service
    ports:
      - '8065:8065'
    depends_on:
      catalog-db:
        condition: service_started
      config-service:
        condition: service_healthy
      registry-service:
        condition: service_healthy

volumes:
  movies-db:
    name: dh-movies-db-volume
  series-db:
    name: dh-series-db-volume
  catalog-db:
    name: dh-catalog-db-volume
  rabbitmq:
    name: dh-rabbitmq-volume